name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make -j
    - uses: actions/upload-artifact@v1
      with:
        name: kernel.elf
        path: o.qemu/kernel.elf
	- name: install dependencies
	  run: sudo apt-get install -y mtools parted
    - name: make boot.img
      run: make -j o.qemu/boot.img