name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build kernel
      run: make -j
    - name: Upload kernel
      uses: actions/upload-artifact@v1
      with:
        name: kernel
        path: |
          output/kernel.elf
          output/ward.efi
    - name: Install QEMU
      run: sudo apt-get update && sudo apt-get install -y qemu-system-x86
    - name: Unit tests
      run: make qemu-test
    - name: Install mtools
      run: sudo apt-get update && sudo apt-get install -y mtools
    - name: Build disk images
      run: make -j disks
    - name: Upload disk images
      uses: actions/upload-artifact@v2
      with:
        name: disks
        path: |
          output/ward.img
          output/ward.vhdx
          output/ward.vmdk
          output/ward.vdi
